apiVersion: batch/v1
kind: Job
metadata:
  name: dreaming-agent
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: dreaming-agent
    spec:
      priorityClassName: dreaming-low
      restartPolicy: Never
      containers:
      - name: agent
        image: python:3.11-slim
        args: ["bash","-lc","pip install numpy && python - << 'PY'\nprint('dreaming step')\nPY"]
        resources:
          requests:
            cpu: "10m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
